#
# ~/.bashrc
#

export PATH="~/.local/bin:$PATH"

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

eval "$(starship init bash)"

[[ $- == *i* ]] && source /usr/share/blesh/ble.sh

eval "$(atuin init bash)"

eval "$(zoxide init bash)"
