#! /usr/bin/bash

# Fail script if any command fails
set -e

# Echo commands
# set -x

## keep track of the last executed command
trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
## echo an error message before exiting
trap 'echo "\"${last_command}\" command failed with exit code $?."' EXIT

# Setup where everything goes
# BACKGROUNDS_DIR=~/Documents/Personal/Dropbox/TamaraDocuments/Backgrounds
# BACKGROUNDS_DIR=~/Documents/Personal/Dropbox/Pictures/SharedBackgrounds
BACKGROUNDS_DIR=~/Documents/Dropbox/Pictures/SharedBackgrounds
THEME_DIRS="Default $(name_time_period)"
PERSON_SPECIFIC=~/Documents/Personal/Dropbox/Pictures/SharedBackgrounds/${USER}Specific

echo "BACKGROUNDS_DIR is: " $BACKGROUNDS_DIR
echo "THEME_DIRS are: " $THEME_DIRS
echo "PERSON_SPECIFIC is: " $PERSON_SPECIFIC
feh --no-fehbg --bg-max $(images_matching_subdirectories --names-only --limit 4 $PERSON_SPECIFIC $BACKGROUNDS_DIR $THEME_DIRS)
