#! /usr/bin/bash

# Fail script if any command fails
set -e

# Echo commands
# set -x

## keep track of the last executed command
trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
## echo an error message before exiting
trap 'echo "\"${last_command}\" command failed with exit code $?."' EXIT

# Setup where everything goes
DROPBOX_LOCATION=$(find ~/Documents -type d -name Dropbox -print -quit)
BACKGROUNDS_DIR="$DROPBOX_LOCATION/Pictures/SharedBackgrounds"
PERSON_SPECIFIC="${USER}Specific"
THEME_DIRS="$PERSON_SPECIFIC Default $(name_time_period)"

echo "DROPBOX_LOCATION is: " $DROPBOX_LOCATION
echo "BACKGROUNDS_DIR is: " $BACKGROUNDS_DIR
echo "PERSON_SPECIFIC is: " $PERSON_SPECIFIC
echo "THEME_DIRS are: " $THEME_DIRS
feh --no-fehbg --bg-max $(images_matching_subdirectories --names-only --limit 4 $BACKGROUNDS_DIR $THEME_DIRS)
