[General]
APPID=30139089f1f08b98e4c16ef46f884148
CitiesTranslation={}
City=Barrie
CityList=['Barrie_CA_5894171']
Country=CA
FontTray="Sans Serif,36,-1,5,50,0,0,0,0,0"
ID=5894171
IconsTheme=OpenWeatherMap
Interval=120
Proxy=False
SystemIcons=hicolor
Toggle_tray_interval=0
Tray=Temperature
TrayColor=#000000
TrayType=temp
Unit=metric
Wind_unit=df

[Logging]
Level=INFO

[MainWindow]
Geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\f\"\0\0\0\xde\0\0\r}\0\0\x3v\0\0\f#\0\0\0\xdf\0\0\r|\0\0\x3u\0\0\0\0\0\0\0\0\a\x80\0\0\f#\0\0\0\xdf\0\0\r|\0\0\x3u)
State=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\0\0\0\0\xc6\0\0\x1z\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\0)

[SearchCity]
Geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x4_\0\0\x1k\0\0\a~\0\0\x2\x95\0\0\x4`\0\0\x1l\0\0\a}\0\0\x2\x94\0\0\0\0\0\0\0\0\a\x80\0\0\x4`\0\0\x1l\0\0\a}\0\0\x2\x94)
