#!/usr/bin/env bash

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

#set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-scale $SCRIPTPATH/down.jpg
fi

leftwm-command "UnloadTheme"

pkill compton
pkill picom
pkill polybar

pkill volumeicon
pkill polkit-gnome-authentication-agent-1
pkill variety
pkill dropbox
pkill nm-applet
pkill xfce4-power-manager
pkill pamac-tray
pkill udiskie
pkill xcape
pkill discord
pkill slack
