#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

function run_if_exists {
    echo tryingto run $1
    if [ -x "$(command -v $1)" ]; then
        echo running $1
        "$1" &> /dev/null &
        echo ran $1
    fi
}


#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down


#boot picom or compton if it exists
if [ -x "$(command -v picom)" ]; then
  picom &> /dev/null &
elif [ -x "$(command -v compton)" ]; then
  compton &> /dev/null &
fi

#set the theme.toml config
leftwm-command "LoadTheme $SCRIPTPATH/theme.toml"

#set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-scale $SCRIPTPATH/background.jpg
fi

#set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-scale $SCRIPTPATH/background.jpg
fi

# setup keyboard map stuff
if [ -x "$(command -v setxkbmap)" ]; then
    setxkbmap -model thinkpad -layout us -variant dvorak -option 'ctrl:nocaps'
fi
if [ -x "$(command -v xcape)" ]; then
    xcape -e 'Control_L=Escape'
fi

index=0
monitor="$(polybar -m | grep +0+0 | sed s/:.*// | tac)"
leftwm-state -q -n -t $SCRIPTPATH/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x y
do
  barname="mainbar$index"
  monitor=$monitor offsetx=$x width=$width polybar -c $SCRIPTPATH/polybar.config $barname &> /dev/null &
  let index=index+1
done

run_if_exists "/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1"
run_if_exists "variety"
run_if_exists "dropbox"
run_if_exists "nm-applet"
run_if_exists "xfce4-power-manager"
run_if_exists "pamac-tray"
run_if_exists "udiskie"
run_if_exists "slack"
run_if_exists "discord"

