#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '


eval "$(starship init bash)"

[[ -s "/home/fprice/.gvm/scripts/gvm" ]] && source "/home/fprice/.gvm/scripts/gvm"