theme = "solarized-dark"
icons = "awesome5"

[[block]]
block = "supertoggle"

command_current_state="timew; timew day"
command_on="timew continue"
command_off="timew stop"

format_on="TW [ {tags} ] {hours}:{minutes}"
format_off="TW IDLE"

command_status_on_regex="(?m)(?s)Tracking\\s+(?P<tags>\\w*).*Tracked\\s+(?P<hours>\\d{1,2}):(?P<minutes>\\d{1,2}):(?P<seconds>\\d{1,2})"
command_status_off_regex="(?m)There is no active time tracking\\.$"

interval = 60

[[block]]
block = "pomodoro"
length = 25
break_length = 5
message = "Take a break!"
break_message = "Back to work!"
notifier = "notifysend"

# [[block]]
# block = "battery"
# interval = 10
# format = "{percentage} {time}"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "time"
interval = 5
format = "%a %Y/%m/%d %R"
