# local.toml can "include" another file - more on this in the next section.
includes = [".dotter/secrets.toml"]
# includes = [".dotter/linux.toml"]

# An array of the names of all packages that are selected.
# Only the files and variables that belong to packages in this list are kept.
# Note that in this example, the `graphics` package is automatically added as well.
packages = ["alacritty","autorandr","fish","flake8","i3","mypy","hub","nvim","user","rclone","wezterm","yamllint","ssh","local","activestate","pivotal","aws","todoist","mutt","gist","gitconfig","dropbox","i3status-rust","bash","sound","picom","i3-scrot","jira","keyd","X11","pipewire","xmonad","wired","meteo-qt","nyxt","reflector","makepkg","wireguard","medium","makepkg"]

# File target locations can be overridden in local.toml
# This can be useful for example for applications which read from a different
#  location depending on the platform.
# Disabling files is possible by setting them to the special value "".
[files]
# Xinitrc = "~/.my_Xinitrc"
# polybar = ""

# I need to define some machine-specific variables.
[variables]
#network_interface = "wlan0"
#screen_size = "1920x1080"
#terminal = "xfce4-terminal"
# Actually, I want the font size on this screen to be a bit bigger.
# Any variables defined in local.toml override variables in global.toml.
# Unlike files, it's impossible to delete variables.
# font_size = 18

leftwm_theme="FrederickPrice"

