[dropbox.variables.dropbox]
    username="rickandtamara@pricemail.ca"

[user.variables.user]
    username="tprice"
    email=""
    fullname=""
    shell="/bin/fish"
    editor="vim"

[mutt.variables.gmail]
    imap_user=""
    imap_pass=""

