#! /bin/sh

# Fail script if any command fails
set -e

## keep track of the last executed command
trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
## echo an error message before exiting
trap 'echo "\"${last_command}\" command failed with exit code $?."' EXIT

echo "Need to copy the .ssh and .gnupg directories over from an existing machine"
echo "You may need to run <udiskie &> and then <pcmanfm &> to get the files across"
echo
echo "After copying the directory, and not before..."

echo "Press any key to continue"
while [ true ] ; do
# read -t 3 -n 1
read -n 1
if [ $? = 0 ] ; then
break ;
else
echo "waiting for the keypress"
fi
done
