#! /bin/sh

# Fail script if any command fails
set -e

## keep track of the last executed command
trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
## echo an error message before exiting
trap 'echo "\"${last_command}\" command failed with exit code $?."' EXIT

PASSWORD_STORE_LOCATION=~/.password-store
if [ ! -d $PASSWORD_STORE_LOCATION ] ; then

    git clone git@github.com:rickprice/password.git $PASSWORD_STORE_LOCATION

fi
