#! /bin/sh

# Fail script if any command fails
set -e

## keep track of the last executed command
trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
## echo an error message before exiting
trap 'echo "\"${last_command}\" command failed with exit code $?."' EXIT

# Configure for ZSH
rm -f ~/.zshrc
rm -f ~/.p10k.zsh
rm -f ~/.zshenv
rm -f ~/.profile
stow --dotfiles zshrc
