#! /bin/bash

# Fail script if any command fails
set -e

## keep track of the last executed command
trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
## echo an error message before exiting
trap 'echo "\"${last_command}\" command failed with exit code $?."' EXIT

## Install reflector
yay --noconfirm -S reflector

## Setup mirrors better
sudo reflector --age 24 --latest 20 --fastest 20 --threads 20 --sort rate --protocol https --save /etc/pacman.d/mirrorlist && true
# sudo reflector --country Canada,UnitedStates --age 24 --protocol https --save /etc/pacman.d/mirrorlist && true

sudo pacman -Sy
yay -Sy
