#! /bin/bash

# Fail script if any command fails
set -e

## keep track of the last executed command
trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
## echo an error message before exiting
trap 'echo "\"${last_command}\" command failed with exit code $?."' EXIT

## Install Main packages I want
sudo pacman --noconfirm -S base-devel
sudo pacman --noconfirm -S stow
sudo pacman --noconfirm -S python
sudo pacman --noconfirm -S python-pip
sudo pacman --noconfirm -S figlet
sudo pacman --noconfirm -S fd
sudo pacman --noconfirm -S tmux
sudo pacman --noconfirm -S zip
sudo pacman --noconfirm -S unzip
sudo pacman --noconfirm -S zenity
sudo pacman --noconfirm -S tlp tlp-rdw acpi_call
sudo pacman --noconfirm -S enscript
sudo pacman --noconfirm -S psutils
sudo pacman --noconfirm -S dos2unix
sudo pacman --noconfirm -S xorg-xev

## Install AUR packages I want
yay --noconfirm -S poppler
yay --noconfirm -S pdfjam
yay --noconfirm -S pass
yay --noconfirm -S udiskie
yay --noconfirm -S go
yay --noconfirm -S x11-ssh-askpass
yay --noconfirm -S mosh
yay --noconfirm -S googler
yay --noconfirm -S so-git
# yay --noconfirm -S luakit-git
yay --noconfirm -S fwupd
yay --noconfirm -S bazelisk-bin
yay --noconfirm -S meld
yay --noconfirm -S aws-cli
yay --noconfirm -S postgresql-libs # Needed for ActiveState BE tools
yay --noconfirm -S python-psycopg2 # Needed for DA importer go utilities
yay --noconfirm -S python-pipenv # Needed for BE tools
yay --noconfirm -S pyenv # Needed for BE tools
yay --noconfirm -S autorandr
yay --noconfirm -S arandr
yay --noconfirm -S ripgrep
yay --noconfirm -S jpegoptim # Lets you reduce size of JPEGs to fit
yay --noconfirm -S inetutils
yay --noconfirm -S trash-cli

# Stuff to read X Window information
yay --noconfirm -S xdotool

# Ensure we have my favourite file manager and the thumbnailers it needs
yay --noconfirm -S pcmanfm tumbler poppler-glib ffmpegthumbnailer freetype2 libgsf raw-thumbnailer ufraw-thumbnailer file-roller atril evince

## X11 stuff
sudo pacman --noconfirm -S xcape

## Keypass
yay --noconfirm -S keepassxc

## Klogg
yay --noconfirm -S klogg

## Git-LFS
yay --noconfirm -S git-lfs
git lfs install

## Man packages
yay --noconfirm -S man-db

## Remmina
yay --noconfirm -S remmina
yay --noconfirm -S freerdp

## Dotter
yay --noconfirm -S dotter-rs-git

## Delta
yay --noconfirm -S git-delta-git

## Perl
sudo pacman --noconfirm -S perl
sudo pacman --noconfirm -S perl-local-lib
SHELL=/bin/bash
eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
sudo pacman --noconfirm -S perl-archive-zip
yay --noconfirm -S cpanminus

## Lazy Git is a lifechanger for Git
yay --noconfirm -S lazygit

## For handling mice and touchpads
yay --noconfirm -S xorg-xinput
yay --noconfirm -S solaar

## lfs is an improved du
yay --noconfirm -S lfs

## xpub lets you figure out your X variables more or less anywhere
yay --noconfirm -S xpub

## Github command line
yay --noconfirm -S github-cli

## Seems to be needed for Perl for the epson printer drivers
# yay --noconfirm -S perl-list-allutils

## Handwriting notetaking software
yay --noconfirm -S xournalpp

