#! /bin/bash

# Fail script if any command fails
set -e

## keep track of the last executed command
trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
## echo an error message before exiting
trap 'echo "\"${last_command}\" command failed with exit code $?."' EXIT

## Install Main packages I want
sudo pacman --noconfirm -S base-devel
sudo pacman --noconfirm -S stow
sudo pacman --noconfirm -S python
sudo pacman --noconfirm -S python-pip
sudo pacman --noconfirm -S figlet
sudo pacman --noconfirm -S fd
sudo pacman --noconfirm -S tmux
sudo pacman --noconfirm -S zip
sudo pacman --noconfirm -S unzip
sudo pacman --noconfirm -S zenity
sudo pacman --noconfirm -S tlp tlp-rdw acpi_call

## Install AUR packages I want
paru --noconfirm -S poppler
paru --noconfirm -S pdfjam
paru --noconfirm -S pass
paru --noconfirm -S udiskie
paru --noconfirm -S go
paru --noconfirm -S x11-ssh-askpass
paru --noconfirm -S mosh
paru --noconfirm -S googler
paru --noconfirm -S so-git
# paru --noconfirm -S luakit-git
paru --noconfirm -S fwupd
paru --noconfirm -S bazelisk-bin
paru --noconfirm -S meld
paru --noconfirm -S aws-cli
paru --noconfirm -S postgresql-libs # Needed for ActiveState BE tools
paru --noconfirm -S python-psycopg2 # Needed for DA importer go utilities
paru --noconfirm -S python-pipenv # Needed for BE tools
paru --noconfirm -S pyenv # Needed for BE tools
paru --noconfirm -S autorandr
paru --noconfirm -S arandr
paru --noconfirm -S ripgrep
paru --noconfirm -S jpegoptim # Lets you reduce size of JPEGs to fit

# Stuff to read X Window information
paru --noconfirm -S xdotool

# Ensure we have my favourite file manager and the thumbnailers it needs
paru --noconfirm -S pcmanfm tumbler poppler-glib ffmpegthumbnailer freetype2 libgsf raw-thumbnailer ufraw-thumbnailer

## X11 stuff
sudo pacman --noconfirm -S xcape

## Keypass
paru --noconfirm -S keepassxc

## Klogg
paru --noconfirm -S klogg

## Git-LFS
paru --noconfirm -S git-lfs
git lfs install

## Man packages
paru --noconfirm -S man-db

## Remmina
paru --noconfirm -S remmina
paru --noconfirm -S freerdp

## Dotter
paru --noconfirm -S dotter-rs-git

## Delta
paru --noconfirm -S git-delta-git

## Perl
sudo pacman --noconfirm -S perl
sudo pacman --noconfirm -S perl-local-lib
SHELL=/bin/bash
eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
sudo pacman --noconfirm -S perl-archive-zip
paru --noconfirm -S cpanminus
