#! /bin/sh

# Fail script if any command fails
set -e

## keep track of the last executed command
trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
## echo an error message before exiting
trap 'echo "\"${last_command}\" command failed with exit code $?."' EXIT

HOME_REPOT_REPOSITORY=git@github.com:ActiveState/TheHomeRepot.git
HOME_REPOT_NAME=TheHomeRepot

CAMEL_REPOSITORY=git@github.com:ActiveState/camel.git
CAMEL_NAME=camel

# Make sure the directory exists
mkdir -p ~/Documents/ActiveState || true

function git_clone() {
    local git_repository="$1"
    local directory_name="$2"
    local directory=~/Documents/ActiveState/$directory_name

    if [ ! -d "$directory" ] ; then

        # Check out the repository
        git clone "$git_repository" "$directory"

        # LFS
        pushd .
        cd $directory

        git lfs install
        git lfs fetch
        git lfs checkout

        popd

        # Create a link in the home directory
        ln -s  $directory ~/$directory_name
    fi
}

git_clone "$HOME_REPOT_REPOSITORY" "$HOME_REPOT_NAME"
git_clone "$CAMEL_REPOSITORY" "$CAMEL_NAME"
