#! /bin/bash

# Fail script if any command fails
set -e

## keep track of the last executed command
trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
## echo an error message before exiting
trap 'echo "\"${last_command}\" command failed with exit code $?."' EXIT

sudo pacman --noconfirm -S pulseaudio pulseaudio-alsa pulseaudio-bluetooth pa-applet-git pavucontrol
yay --noconfirm -S pa-applet-git

sudo pacman --noconfirm -S sof-firmware
