#! /bin/bash

# Fail script if any command fails
set -e

## keep track of the last executed command
trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
## echo an error message before exiting
trap 'echo "\"${last_command}\" command failed with exit code $?."' EXIT

sudo pacman --noconfirm -S pulseaudio pulseaudio-bluetooth
paru --noconfirm -S pa-applet-git pavucontrol

# Needed for Lenovo Thinkpad X1 to have onboard and HDMI sound to work
sudo pacman --noconfirm -S sof-firmware

# Needed for awesomeWM sound widget to work
sudo pacman --noconfirm -S alsa-utils

# Probably needed for switching audio automatically
# paru --noconfirm -S alsa-plugins

# Switching to Pipewire
sudo pacman -S pipewire-pulse pipewire-jack pipewire-alsa wireplumber qpwgraph

