#! /bin/bash

# Fail script if any command fails
set -e

## keep track of the last executed command
trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
## echo an error message before exiting
trap 'echo "\"${last_command}\" command failed with exit code $?."' EXIT

# Moving files to and from DropBox
yay --noconfirm -S rclone

# For handling Magnet and BitTorrent links
yay --noconfirm -S tixati
