#! /bin/bash

# Fail script if any command fails
set -e

## keep track of the last executed command
trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
## echo an error message before exiting
trap 'echo "\"${last_command}\" command failed with exit code $?."' EXIT

# Add ourselves to the lp group so we can access bluetooth
sudo groupadd --force lp  # Force to avoid errors when group exists already
sudo usermod -aG lp $USER

sudo pacman --noconfirm -S bluez bluez-utils bluez-hid2hci blueman
sudo systemctl enable bluetooth

sudo systemctl enable bluetooth
sudo systemctl start bluetooth
