#! /bin/bash

# Fail script if any command fails
set -e

## keep track of the last executed command
trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
## echo an error message before exiting
trap 'echo "\"${last_command}\" command failed with exit code $?."' EXIT

## Setup DropBox

yay --noconfirm -S python-gpgme
yay --noconfirm -S qt5-base
yay --noconfirm -S dropbox

# From the Arch Wiki Prevent Automatic updates which always go wrong...
rm -rf ~/.dropbox-dist
install -dm0 ~/.dropbox-dist
