#! /bin/bash

# Fail script if any command fails
set -e

## keep track of the last executed command
trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
## echo an error message before exiting
trap 'echo "\"${last_command}\" command failed with exit code $?."' EXIT

## Fonts
paru --noconfirm -S xorg-xfontsel
# paru --noconfirm -S nerd-fonts-complete
paru --noconfirm -S ttf-iosevka
paru --noconfirm -S noto-fonts
paru --noconfirm -S noto-fonts-emoji
paru --noconfirm -S noto-fonts-extra
paru --noconfirm -S ttf-linux-libertine
paru --noconfirm -S powerline-fonts
paru --noconfirm -S adobe-source-code-pro-fonts
paru --noconfirm -S ttf-font-awesome

# Cambria, Garamond, Mongolian Baiti, Palatina Linotype, Segeo UI
paru --noconfirm -S ttf-vista-fonts # Cambria
paru --noconfirm -S ebgaramond-otf  # Garamond

# Fonts for Amazon stuff
paru --noconfirm -S amazon-fonts  # Bookerly, Amazon Ember
