#! /bin/sh

# Fail script if any command fails
set -e

## keep track of the last executed command
trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
## echo an error message before exiting
trap 'echo "\"${last_command}\" command failed with exit code $?."' EXIT

# Make sure the directory exists
mkdir -p ~/Documents/Personal/Repositories || true

function git_clone() {
    local git_repository="$1"
    local directory_name="$2"
    local directory=~/Documents/Personal/Repositories/$directory_name

    if [ ! -d "$directory" ] ; then

        # Check out the repository
        git clone "$git_repository" "$directory"

        # LFS
        pushd .
        cd $directory

        git lfs install
        git lfs fetch
        git lfs checkout

        popd

        # Create a link in the home directory
        ln -s  $directory ~/$directory_name
    fi
}

git_clone "git@github.com:rickprice/VimWikiFiles.git" "vimwiki"
