#! /bin/bash

# Fail script if any command fails
set -e

## keep track of the last executed command
trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
## echo an error message before exiting
trap 'echo "\"${last_command}\" command failed with exit code $?."' EXIT

paru --noconfirm -S ntfs-3g
paru --noconfirm -S ntfsprogs
paru --noconfirm -S dosfstools
paru --noconfirm -S gnome-disk-utility # Gives us gnome-disks
paru --noconfirm -S gparted # Gives us gparted


# SSD Trimming
paru --noconfirm -S util-linux # Gives us gparted
sudo systemctl enable fstrim.timer
