#! /bin/bash

# Fail script if any command fails
set -e

## keep track of the last executed command
trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
## echo an error message before exiting
trap 'echo "\"${last_command}\" command failed with exit code $?."' EXIT

## i3 things
# paru --noconfirm -S dmenu-frecency
paru --noconfirm -S dmenu
paru --noconfirm -S i3exit
paru --noconfirm -S polkit-gnome
paru --noconfirm -S nitrogen
paru --noconfirm -S variety
paru --noconfirm -S picom
# paru --noconfirm -S network-manager-applet-git
paru --noconfirm -S xfce4-power-manager
paru --noconfirm -S pamac-aur
paru --noconfirm -S xautolock
# paru --noconfirm -S i3lock-blur
# paru --noconfirm -S ff-theme-util
paru --noconfirm -S volumeicon
paru --noconfirm -S alsa-utils
paru --noconfirm -S i3-scrot
paru --noconfirm -S xorg-xkill
paru --noconfirm -S network-manager-applet
# paru --noconfirm -R i3-wm i3status i3exit || true
#paru --noconfirm -S i3-git i3status-git i3exit
# paru --noconfirm -S i3-git i3status-rust-git i3exit
paru --noconfirm -S i3 i3status-rust i3exit
paru --noconfirm -S dunst
paru --noconfirm -S polkit-gnome


# i3status-rust
paru --noconfirm -S alsa-utils

