#! /bin/bash

# Fail script if any command fails
set -e

## keep track of the last executed command
trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
## echo an error message before exiting
trap 'echo "\"${last_command}\" command failed with exit code $?."' EXIT

## Install Main packages I want

## Install AUR packages I want
yay --noconfirm -S keymapper

## Setup services
systemctl enable keymapperd
