#! /bin/bash

# Fail script if any command fails
set -e

## keep track of the last executed command
trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
## echo an error message before exiting
trap 'echo "\"${last_command}\" command failed with exit code $?."' EXIT

## Install Luakit with the ability to play DRM content like YouTube
sudo pacman --noconfirm -S  gst-plugins-good
sudo pacman --noconfirm -S  gst-plugins-bad
sudo pacman --noconfirm -S luakit-git
