#! /bin/bash

# Fail script if any command fails
set -e

## keep track of the last executed command
trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
## echo an error message before exiting
trap 'echo "\"${last_command}\" command failed with exit code $?."' EXIT

## Neovim
paru --noconfirm -S neovim-nightly-bin

## Required for Neovim
sudo pip install neovim
sudo pacman --noconfirm -S nodejs
sudo pacman --noconfirm -S npm
sudo npm install -g neovim
sudo pacman --noconfirm -S ruby
gem install neovim
# sudo cpanm Neovim::Ext
# Can't use noconfirm with this because it defaults to N to delete vi and Vim
yes | LC_ALL=en_US.UTF-8 paru -S neovim-symlinks
paru --noconfirm -S xclip

# Language Servers
paru --noconfirm -S pyright-git
paru --noconfirm -S bash-language-server
paru --noconfirm -S gopls
paru --noconfirm -S vim-language-server
paru --noconfirm -S yaml-language-server
paru --noconfirm -S tree-sitter-c
paru --noconfirm -S tree-sitter-cpp

#paru --noconfirm -S ctags

# Markdown
# paru --noconfirm -S glow

# Shell
paru --noconfirm -S shellcheck

# Perl
cpanm -n Neovim::Ext
