#! /bin/bash

# Fail script if any command fails
set -e

## keep track of the last executed command
trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
## echo an error message before exiting
trap 'echo "\"${last_command}\" command failed with exit code $?."' EXIT

# Geolocating
paru --noconfirm -S perl-image-exiftool
paru --noconfirm -S gpsbabel
paru --noconfirm -S python-ijson

# Photographic processing
paru --noconfirm -S rawtherapee
paru --noconfirm -S gimp
paru --noconfirm -S perl-image-exiftool
paru --noconfirm -S nomacs
paru --noconfirm -S imagemagick
paru --noconfirm -S openexr
paru --noconfirm -S dcraw
paru --noconfirm -S gnuplot
paru --noconfirm -S darktable
paru --noconfirm -S hugin
paru --noconfirm -S gphoto2

# Collages
paru --noconfirm -S photocollage

# Drawing
paru --noconfirm -S inkscape

# Ensure we have my favourite file manager and the thumbnailers it needs
paru --noconfirm -S pcmanfm tumbler poppler-glib ffmpegthumbnailer freetype2 libgsf raw-thumbnailer ufraw-thumbnailer
