#! /bin/bash

# Fail script if any command fails
set -e

## keep track of the last executed command
trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
## echo an error message before exiting
trap 'echo "\"${last_command}\" command failed with exit code $?."' EXIT

# Setup Epson ET-2720 printer
sudo pacman --noconfirm -Sy patch
yay --noconfirm -S epson-inkjet-printer-escpr
sudo pacman --noconfirm -Sy cups cups-pdf
sudo gpasswd -a `whoami` lp
# ! Doesn't seem to be needed
# sudo gpasswd -a `whoami` lpadmin
# sudo systemctl start org.cups.cupsd.service
# sudo systemctl enable org.cups.cupsd.service
# ! Doesn't seem to be needed
