#! /bin/bash

# Fail script if any command fails
set -e

## keep track of the last executed command
trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
## echo an error message before exiting
trap 'echo "\"${last_command}\" command failed with exit code $?."' EXIT

## Needed for Brother MFC-L2700DW
PRINTER_IP="192.168.50.253"

### Setup Brother scanner
yay --noconfirm -S brother-mfc-l2710dw
yay --noconfirm -S brscan4
sudo pacman --noconfirm -S simple-scan
sudo brsaneconfig4 -a name=BROTHER model=MFC-L2700DW ip="$PRINTER_IP"
# Seems you can also do this:
# brsaneconfig4 -a name=BROTHER model=MFC-L2700DW nodename=BRWD85DE244E1EB

### Setup Brother Printer
sudo pacman --noconfirm -S cups
sudo systemctl enable cups.service
sudo systemctl start cups.service
sudo pacman --noconfirm -S cups system-config-printer
lpadmin -p MFC-L2700DW -E -v "ipp://$PRINTER_IP/ipp/print" -m everywhere
