#! /bin/bash

# Fail script if any command fails
set -e

## keep track of the last executed command
trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
## echo an error message before exiting
trap 'echo "\"${last_command}\" command failed with exit code $?."' EXIT

### Setup NTP
# sudo pacman --noconfirm -S ntp

### Setup NTP Service
# sudo systemctl enable ntpd.service
# sudo systemctl start ntpd.service

### Chrony
# This will install Chrony as well, two for one...
paru --noconfirm -S networkmanager-dispatcher-chrony

sudo systemctl enable chronyd.service
sudo systemctl start chronyd.service
