#! /bin/bash

# Fail script if any command fails
set -e

## keep track of the last executed command
trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
## echo an error message before exiting
trap 'echo "\"${last_command}\" command failed with exit code $?."' EXIT

# Video
paru --noconfirm -S vlc
paru --noconfirm -S flowblade

# OpenCL

paru --noconfirm -S intel-opencl-sdk
paru --noconfirm -S intel-compute-runtime
paru --noconfirm -S dmidecode
paru --noconfirm -S clinfo


