#! /bin/bash

# Fail script if any command fails
set -e

## keep track of the last executed command
trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
## echo an error message before exiting
trap 'echo "\"${last_command}\" command failed with exit code $?."' EXIT

## i3 things
# paru --noconfirm -S dmenu-frecency-git
paru --noconfirm -S i3exit
paru --noconfirm -S polkit-gnome
# paru --noconfirm -S nitrogen
paru --noconfirm -S variety
paru --noconfirm -S picom
# paru --noconfirm -S network-manager-applet-git
paru --noconfirm -S xautolock
# paru --noconfirm -S i3lock-blur
# paru --noconfirm -S ff-theme-util
paru --noconfirm -S alsa-utils
paru --noconfirm -S i3-scrot
paru --noconfirm -S xorg-xkill
paru --noconfirm -S xorg-xwininfo
# paru --noconfirm -S network-manager-applet
#paru --noconfirm -R i3-wm i3status i3exit || true
#paru --noconfirm -S i3-git i3status-git i3exit
#paru --noconfirm -S i3-git i3status-rust-git i3exit
#paru --noconfirm -S i3-git
#paru --noconfirm -S dunst
#paru --noconfirm -S polkit-gnome

# i3status-rust
paru --noconfirm -S i3status-rust alsa-utils

# Now LeftWM specific dependencies
#paru --noconfirm -S leftwm-git
#paru --noconfirm -S leftwm-theme-git
#paru --noconfirm -S polybar-git

# Awesome Window Manager
paru --noconfirm -R awesome
paru --noconfirm -S awesome-git
paru --noconfirm -S rlwrap dex vicious
paru --noconfirm -S alsa-utils pulseaudio pavucontrol
git clone git@github.com:streetturtle/awesome-wm-widgets.git ~/.config/awesome/awesome-wm-widgets

# XMonad Window Manager
paru --noconfirm -S git xorg-server xorg-apps xorg-xinit xorg-xmessage libx11 libxft libxinerama libxrandr libxss pkgconf
paru --noconfirm -S xmonad xmonad-contrib
paru --noconfirm -S xmobar-dynamic
paru --noconfirm -S trayer-srg
paru --noconfirm -S xorg-fonts-misc
paru --noconfirm -S wired # toaster notification manager
paru --noconfirm -S feh
paru --noconfirm -S gnome-system-monitor
paru --noconfirm -S dmenu-frecency-git
paru --noconfirm -S volumeicon
paru --noconfirm -S xfce4-power-manager
paru --noconfirm -S pamac-aur
paru --noconfirm -S network-manager-applet
paru --noconfirm -S xmlstarlet
paru --noconfirm -S meteo-gtk
paru --noconfirm -S meteo-qt
paru --noconfirm -S ttf-weather-icons
