#! /bin/bash

# Fail script if any command fails
set -e

## keep track of the last executed command
trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
## echo an error message before exiting
trap 'echo "\"${last_command}\" command failed with exit code $?."' EXIT

# Ensure we have a writable bin directory on the path
mkdir -p ~/.local/bin
export PATH=$PATH:~/.local/bin

# ActiveState tool
yes | sh <(curl -q https://platform.activestate.com/dl/cli/install.sh)

# ActiveState BE Tooling
paru --noconfirm -S yarn
# ! I'm really not sure why this is already installed, need to loop back and look at this
# paru --noconfirm -S node
# ! I'm really not sure why this is already installed, need to loop back and look at this
paru --noconfirm -S prettier
paru --noconfirm -S jq
paru --noconfirm -S jqp -- GUI Interface to JQ
paru --noconfirm -S yq
paru --noconfirm -S gron
paru --noconfirm -S python37
paru --noconfirm -S python-black
paru --noconfirm -S python-isort
paru --noconfirm -S mypy
paru --noconfirm -S perl-tidy
# paru --noconfirm -S python-requests-cache


# Hub
paru --noconfirm -S hub

# BE Tools setup
# We really don't need this to be run AFAIK, and it has issues when run here...
# ~/TheHomeRepot/install-dev-tools.sh

# VPN stuff for ActiveState
paru --noconfirm -S networkmanager-openvpn

# Ansible stuff for ActiveState
paru --noconfirm -S python-ansible
paru --noconfirm -S python-pywinrm


# 1Password
paru --noconfirm -S 1password
