#! /bin/bash

# Fail script if any command fails
set -e

## keep track of the last executed command
trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
## echo an error message before exiting
trap 'echo "\"${last_command}\" command failed with exit code $?."' EXIT

## Setup ZSH for humans
# ZSH for Humans already setup, so reuse config
# if command -v curl >/dev/null 2>&1; then
#   sh -c "$(curl -fsSL https://raw.githubusercontent.com/romkatv/zsh4humans/v4/install)"
# else
#   sh -c "$(wget -O- https://raw.githubusercontent.com/romkatv/zsh4humans/v4/install)"
# fi
#
# chsh -s $(which zsh)

# install the fish shell
yay --noconfirm -S fish
# Firsher plugin manager
yay --noconfirm -S fisher-git

# fzf plugin
yay --noconfirm -S fzf-git
# yay --noconfirm -S fzf-extras-git
yay --noconfirm -S fd
yay --noconfirm -S bat

# Better cd
yay --noconfirm -S zoxide-git

# Default shell is set as fish in initial machine build script
# chsh -s $(which fish)

fish -c "fisher install PatrickF1/fzf.fish"
fish -c "fisher install danhper/fish-ssh-agent"
fish -c "fisher install rickprice/aws_mfa"
fish -c "fisher install rickprice/HomeRepotTools_fish"
