#! /bin/sh

# Fail script if any command fails
set -e

## keep track of the last executed command
trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
## echo an error message before exiting
trap 'echo "\"${last_command}\" command failed with exit code $?."' EXIT

dotter --force

# Needs to be owned by root and executable
sudo chmod a+x /etc/NetworkManager/dispatcher.d/10-dropbox.sh
sudo chown root:root /etc/NetworkManager/dispatcher.d/10-dropbox.sh

# rm -rf ~/.config/mimeapps.list
# stow --dotfiles config
# stow --dotfiles local
# stow --dotfiles tmux
# stow --dotfiles mutt
# stow --dotfiles weechat
# stow --dotfiles ssh
