#! /bin/bash

# Fail script if any command fails
set -e

## keep track of the last executed command
trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
## echo an error message before exiting
trap 'echo "\"${last_command}\" command failed with exit code $?."' EXIT

# Base timeshift
yay --noconfirm -S timeshift

# Turn on autosnap last because during an initial install it does too many snapshots
yay --noconfirm -S timeshift-autosnap
